language: node_js
node_js:
  - node

before_script:
    - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | sudo bash"

script:
  # your build scripts before running `fossa`
  # NOTE: before running `fossa` make sure to save your FOSSA_API_KEY in your
  # environment variable in Travis see below.
  - export FOSSA_API_KEY=3067e13ad55fd2f97b22bc73618a6f60
  - fossa analyze